In [4]:
from pathlib import Path

import pandas as pd


DATA_PATH = Path("data") / "housing" / "housing.csv"

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Dataset not found: {DATA_PATH}")

housing = pd.read_csv(DATA_PATH)

In [4]:
print(housing.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0
1    -122.22     37.86                21.0       7099.0          1106.0
2    -122.24     37.85                52.0       1467.0           190.0
3    -122.25     37.85                52.0       1274.0           235.0
4    -122.25     37.85                52.0       1627.0           280.0

   population  households  median_income  median_house_value ocean_proximity
0       322.0       126.0         8.3252            452600.0        NEAR BAY
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY
2       496.0       177.0         7.2574            352100.0        NEAR BAY
3       558.0       219.0         5.6431            341300.0        NEAR BAY
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [6]:
housing.tail(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [7]:
print("Shape:", housing.shape)
print("Row count:", housing.shape[0])
print("Column count:", housing.shape[1])

print("\nColumns:")
print(housing.columns)

print("\nIndex:")
print(housing.index)

Shape: (20640, 10)
Row count: 20640
Column count: 10

Columns:
Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

Index:
RangeIndex(start=0, stop=20640, step=1)

In [8]:
housing.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [9]:
housing["ocean_proximity"].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [10]:
housing.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.7 MB

In [11]:
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [5]:
housing.iloc[0]

longitude              -122.23
latitude                 37.88
housing_median_age        41.0
total_rooms              880.0
total_bedrooms           129.0
population               322.0
households               126.0
median_income           8.3252
median_house_value    452600.0
ocean_proximity       NEAR BAY
Name: 0, dtype: object

In [6]:
housing.iloc[:3]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY

In [7]:
housing.loc[100]

longitude               -117.04
latitude                   32.8
housing_median_age         11.0
total_rooms              1802.0
total_bedrooms            440.0
population                630.0
households                428.0
median_income            2.0337
median_house_value     146700.0
ocean_proximity       <1H OCEAN
Name: 100, dtype: object

In [8]:
housing.loc[:, ["median_income", "median_house_value"]]

       median_income  median_house_value
0             8.3252            452600.0
1             8.3014            358500.0
2             7.2574            352100.0
3             5.6431            341300.0
4             3.8462            342200.0
...              ...                 ...
20635         1.5603             78100.0
20636         2.5568             77100.0
20637         1.7000             92300.0
20638         1.8672             84700.0
20639         2.3886             89400.0

[20640 rows x 2 columns]

In [10]:
housing.loc[50:55]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
50,-122.27,37.82,21.0,896.0,453.0,735.0,438.0,0.9218,171900.0,NEAR BAY
51,-122.27,37.82,43.0,1868.0,456.0,1061.0,407.0,1.5045,93800.0,NEAR BAY
52,-122.27,37.82,41.0,3221.0,853.0,1959.0,720.0,1.1108,97500.0,NEAR BAY
53,-122.27,37.82,52.0,1630.0,456.0,1162.0,400.0,1.2475,104200.0,NEAR BAY
54,-122.28,37.82,52.0,1170.0,235.0,701.0,233.0,1.6098,87500.0,NEAR BAY
55,-122.28,37.82,52.0,945.0,243.0,576.0,220.0,1.4113,83100.0,NEAR BAY

In [11]:
housing.loc[:,["longitude", "latitude", "median_income"]]

       longitude  latitude  median_income
0        -122.23     37.88         8.3252
1        -122.22     37.86         8.3014
2        -122.24     37.85         7.2574
3        -122.25     37.85         5.6431
4        -122.25     37.85         3.8462
...          ...       ...            ...
20635    -121.09     39.48         1.5603
20636    -121.21     39.49         2.5568
20637    -121.22     39.43         1.7000
20638    -121.32     39.43         1.8672
20639    -121.24     39.37         2.3886

[20640 rows x 3 columns]

In [13]:
housing[(housing["median_income"]>8) & (housing["ocean_proximity"]=="NEAR OCEAN")]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
546,-122.21,37.38,28.0,4518.0,578.0,1489.0,559.0,11.3176,500001.0,NEAR OCEAN
1244,-122.33,37.55,51.0,2565.0,332.0,870.0,309.0,9.3694,500001.0,NEAR OCEAN
1485,-122.36,37.54,23.0,6184.0,747.0,2165.0,700.0,10.1675,500001.0,NEAR OCEAN
1548,-118.38,33.81,20.0,1975.0,306.0,703.0,292.0,8.5491,410300.0,NEAR OCEAN
1728,-118.36,33.79,34.0,5166.0,704.0,2071.0,668.0,8.3609,500001.0,NEAR OCEAN
...,...,...,...,...,...,...,...,...,...,...
19286,-118.33,33.77,33.0,4244.0,595.0,1534.0,557.0,9.8214,500001.0,NEAR OCEAN
19534,-122.21,37.37,34.0,1476.0,217.0,613.0,223.0,8.2883,500001.0,NEAR OCEAN
20374,-122.27,37.48,26.0,3542.0,507.0,1392.0,524.0,8.5184,500001.0,NEAR OCEAN
20466,-117.24,32.85,22.0,3479.0,448.0,1252.0,440.0,10.0707,500001.0,NEAR OCEAN
20492,-117.18,33.02,15.0,3540.0,453.0,1364.0,425.0,13.6623,500001.0,NEAR OCEAN

In [15]:
housing[housing["ocean_proximity"]=="ISLAND"].count()

longitude             5
latitude              5
housing_median_age    5
total_rooms           5
total_bedrooms        5
population            5
households            5
median_income         5
median_house_value    5
ocean_proximity       5
dtype: int64

In [25]:
housing[housing["ocean_proximity"]=="NEAR OCEAN"].loc[:,["median_income"]].mean()

median_income    4.005785
dtype: float64

In [26]:
housing[housing["median_income"] == housing["median_income"].max()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
515,-118.41,34.07,52.0,3562.0,394.0,1163.0,361.0,15.0001,500001.0,<1H OCEAN
549,-118.33,34.07,52.0,1482.0,171.0,531.0,161.0,15.0001,500001.0,<1H OCEAN
613,-118.33,34.06,52.0,1841.0,240.0,693.0,218.0,15.0001,500001.0,<1H OCEAN
793,-122.44,37.79,52.0,1447.0,186.0,483.0,181.0,15.0001,500001.0,NEAR BAY
954,-118.19,34.19,34.0,2061.0,260.0,825.0,254.0,15.0001,500001.0,<1H OCEAN
1068,-118.43,34.08,46.0,778.0,90.0,238.0,93.0,15.0001,500001.0,<1H OCEAN
1821,-121.96,37.13,26.0,50.0,5.0,17.0,4.0,15.0001,400000.0,<1H OCEAN
2526,-122.20,37.44,31.0,2328.0,270.0,722.0,247.0,15.0001,500001.0,NEAR OCEAN
2533,-122.14,37.50,46.0,30.0,4.0,13.0,5.0,15.0001,500001.0,NEAR BAY
3148,-121.59,37.19,52.0,220.0,32.0,55.0,26.0,15.0001,131300.0,<1H OCEAN
3288,-118.41,34.07,52.0,1202.0,142.0,408.0,138.0,15.0001,500001.0,<1H OCEAN
3555,-118.32,34.06,52.0,955.0,100.0,457.0,120.0,15.0001,500001.0,<1H OCEAN
4304,-118.39,34.08,52.0,3759.0,464.0,1407.0,422.0,15.0001,500001.0,<1H OCEAN
4524,-117.87,33.62,15.0,2209.0,275.0,735.0,274.0,15.0001,500001.0,<1H OCEAN
4614,-117.23,32.99,17.0,2718.0,326.0,1011.0,319.0,15.0001,500001.0,NEAR OCEAN
5941,-121.87,37.46,43.0,91.0,12.0,58.0,16.0,15.0001,500001.0,<1H OCEAN
5999,-118.41,34.09,37.0,2716.0,302.0,809.0,291.0,15.0001,500001.0,<1H OCEAN
6786,-118.20,34.19,38.0,2176.0,266.0,798.0,243.0,15.0001,500001.0,<1H OCEAN
7777,-122.36,37.56,32.0,4684.0,540.0,1512.0,511.0,15.0001,500001.0,NEAR OCEAN
7826,-118.44,34.09,36.0,3129.0,392.0,862.0,334.0,15.0001,500001.0,<1H OCEAN
8592,-118.49,34.06,42.0,2861.0,360.0,829.0,310.0,15.0001,500001.0,<1H OCEAN
8799,-122.50,37.79,52.0,8.0,1.0,13.0,1.0,15.0001,500001.0,NEAR BAY
8857,-122.22,37.44,32.0,4281.0,501.0,1318.0,484.0,15.0001,500001.0,NEAR OCEAN
9644,-122.21,37.46,40.0,1777.0,207.0,577.0,207.0,15.0001,500001.0,NEAR OCEAN
9701,-118.10,34.13,47.0,2234.0,276.0,749.0,260.0,15.0001,500001.0,<1H OCEAN
10431,-118.06,34.15,37.0,1980.0,226.0,697.0,226.0,15.0001,500001.0,INLAND
10601,-118.33,34.07,52.0,2248.0,255.0,813.0,265.0,15.0001,500001.0,<1H OCEAN
11068,-118.37,34.10,37.0,407.0,67.0,100.0,47.0,15.0001,500001.0,<1H OCEAN
11369,-122.18,37.46,40.0,2529.0,293.0,831.0,258.0,15.0001,500001.0,NEAR BAY
11501,-122.27,37.43,33.0,1601.0,223.0,629.0,215.0,15.0001,500001.0,NEAR OCEAN
12500,-118.34,33.76,34.0,5586.0,674.0,1871.0,636.0,15.0001,500001.0,NEAR OCEAN
12674,-118.42,34.09,40.0,3552.0,392.0,1024.0,370.0,15.0001,500001.0,<1H OCEAN
12796,-118.40,34.11,32.0,5578.0,753.0,1567.0,697.0,15.0001,500001.0,<1H OCEAN
12837,-118.49,34.05,42.0,1918.0,216.0,632.0,224.0,15.0001,500001.0,<1H OCEAN
13076,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0,<1H OCEAN
13558,-118.12,34.12,52.0,2907.0,317.0,956.0,279.0,15.0001,500001.0,<1H OCEAN
13814,-122.22,37.40,32.0,2297.0,287.0,814.0,283.0,15.0001,500001.0,NEAR OCEAN
14480,-118.34,34.08,52.0,1721.0,195.0,688.0,196.0,15.0001,500001.0,<1H OCEAN
14520,-118.50,34.05,36.0,4152.0,542.0,1461.0,550.0,15.0001,500001.0,<1H OCEAN
14918,-118.42,34.08,48.0,2413.0,261.0,770.0,248.0,15.0001,500001.0,<1H OCEAN
14984,-118.42,34.08,46.0,1399.0,148.0,410.0,152.0,15.0001,500001.0,<1H OCEAN
15857,-118.18,34.19,48.0,1371.0,NaN,528.0,155.0,15.0001,500001.0,<1H OCEAN
16101,-118.06,33.72,14.0,2665.0,331.0,964.0,319.0,15.0001,500001.0,NEAR OCEAN
17773,-118.40,34.08,52.0,3815.0,439.0,1266.0,413.0,15.0001,500001.0,<1H OCEAN
18825,-118.04,34.13,35.0,249.0,31.0,268.0,29.0,15.0001,500001.0,INLAND
19008,-118.50,34.04,52.0,3000.0,374.0,1143.0,375.0,15.0001,500001.0,<1H OCEAN
19881,-118.40,34.10,27.0,3979.0,510.0,1351.0,520.0,15.0001,500001.0,<1H OCEAN
20183,-117.85,33.62,13.0,5192.0,658.0,1865.0,662.0,15.0001,500001.0,<1H OCEAN
20304,-118.40,34.09,45.0,2686.0,283.0,857.0,259.0,15.0001,500001.0,<1H OCEAN

In [27]:
housing[housing["median_house_value"] == housing["median_house_value"].max()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
89,-122.27,37.80,52.0,249.0,78.0,396.0,85.0,1.2434,500001.0,NEAR BAY
103,-118.47,33.99,24.0,1438.0,454.0,665.0,416.0,2.9750,500001.0,<1H OCEAN
105,-118.50,33.97,29.0,2737.0,808.0,1157.0,696.0,5.1280,500001.0,<1H OCEAN
107,-118.39,34.08,27.0,6605.0,1710.0,2665.0,1520.0,3.8088,500001.0,<1H OCEAN
132,-122.34,37.55,44.0,2465.0,328.0,843.0,324.0,6.9533,500001.0,NEAR OCEAN
...,...,...,...,...,...,...,...,...,...,...
20494,-118.12,34.13,52.0,2935.0,341.0,975.0,327.0,11.7060,500001.0,<1H OCEAN
20500,-121.93,37.66,24.0,3166.0,424.0,1081.0,400.0,8.3337,500001.0,<1H OCEAN
20511,-122.05,37.31,25.0,4111.0,538.0,1585.0,568.0,9.2298,500001.0,<1H OCEAN
20515,-117.36,33.17,24.0,2046.0,442.0,812.0,367.0,2.3182,500001.0,NEAR OCEAN
20535,-122.43,37.80,52.0,2802.0,622.0,954.0,572.0,4.5399,500001.0,NEAR BAY