In [1]:
from pathlib import Path

import pandas as pd


DATA_PATH = Path("data") / "housing" / "housing.csv"

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Dataset not found: {DATA_PATH}")

housing = pd.read_csv(DATA_PATH)

In [4]:
print(housing.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0
1    -122.22     37.86                21.0       7099.0          1106.0
2    -122.24     37.85                52.0       1467.0           190.0
3    -122.25     37.85                52.0       1274.0           235.0
4    -122.25     37.85                52.0       1627.0           280.0

   population  households  median_income  median_house_value ocean_proximity
0       322.0       126.0         8.3252            452600.0        NEAR BAY
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY
2       496.0       177.0         7.2574            352100.0        NEAR BAY
3       558.0       219.0         5.6431            341300.0        NEAR BAY
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [6]:
housing.tail(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [7]:
print("Shape:", housing.shape)
print("Row count:", housing.shape[0])
print("Column count:", housing.shape[1])

print("\nColumns:")
print(housing.columns)

print("\nIndex:")
print(housing.index)

Shape: (20640, 10)
Row count: 20640
Column count: 10

Columns:
Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

Index:
RangeIndex(start=0, stop=20640, step=1)

In [8]:
housing.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [9]:
housing["ocean_proximity"].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [10]:
housing.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.7 MB

In [11]:
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [5]:
housing.iloc[0]

longitude              -122.23
latitude                 37.88
housing_median_age        41.0
total_rooms              880.0
total_bedrooms           129.0
population               322.0
households               126.0
median_income           8.3252
median_house_value    452600.0
ocean_proximity       NEAR BAY
Name: 0, dtype: object

In [6]:
housing.iloc[:3]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY

In [7]:
housing.loc[100]

longitude               -117.04
latitude                   32.8
housing_median_age         11.0
total_rooms              1802.0
total_bedrooms            440.0
population                630.0
households                428.0
median_income            2.0337
median_house_value     146700.0
ocean_proximity       <1H OCEAN
Name: 100, dtype: object

In [8]:
housing.loc[:, ["median_income", "median_house_value"]]

       median_income  median_house_value
0             8.3252            452600.0
1             8.3014            358500.0
2             7.2574            352100.0
3             5.6431            341300.0
4             3.8462            342200.0
...              ...                 ...
20635         1.5603             78100.0
20636         2.5568             77100.0
20637         1.7000             92300.0
20638         1.8672             84700.0
20639         2.3886             89400.0

[20640 rows x 2 columns]

In [10]:
housing.loc[50:55]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
50,-122.27,37.82,21.0,896.0,453.0,735.0,438.0,0.9218,171900.0,NEAR BAY
51,-122.27,37.82,43.0,1868.0,456.0,1061.0,407.0,1.5045,93800.0,NEAR BAY
52,-122.27,37.82,41.0,3221.0,853.0,1959.0,720.0,1.1108,97500.0,NEAR BAY
53,-122.27,37.82,52.0,1630.0,456.0,1162.0,400.0,1.2475,104200.0,NEAR BAY
54,-122.28,37.82,52.0,1170.0,235.0,701.0,233.0,1.6098,87500.0,NEAR BAY
55,-122.28,37.82,52.0,945.0,243.0,576.0,220.0,1.4113,83100.0,NEAR BAY

In [11]:
housing.loc[:,["longitude", "latitude", "median_income"]]

       longitude  latitude  median_income
0        -122.23     37.88         8.3252
1        -122.22     37.86         8.3014
2        -122.24     37.85         7.2574
3        -122.25     37.85         5.6431
4        -122.25     37.85         3.8462
...          ...       ...            ...
20635    -121.09     39.48         1.5603
20636    -121.21     39.49         2.5568
20637    -121.22     39.43         1.7000
20638    -121.32     39.43         1.8672
20639    -121.24     39.37         2.3886

[20640 rows x 3 columns]

In [13]:
housing[(housing["median_income"]>8) & (housing["ocean_proximity"]=="NEAR OCEAN")]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
546,-122.21,37.38,28.0,4518.0,578.0,1489.0,559.0,11.3176,500001.0,NEAR OCEAN
1244,-122.33,37.55,51.0,2565.0,332.0,870.0,309.0,9.3694,500001.0,NEAR OCEAN
1485,-122.36,37.54,23.0,6184.0,747.0,2165.0,700.0,10.1675,500001.0,NEAR OCEAN
1548,-118.38,33.81,20.0,1975.0,306.0,703.0,292.0,8.5491,410300.0,NEAR OCEAN
1728,-118.36,33.79,34.0,5166.0,704.0,2071.0,668.0,8.3609,500001.0,NEAR OCEAN
...,...,...,...,...,...,...,...,...,...,...
19286,-118.33,33.77,33.0,4244.0,595.0,1534.0,557.0,9.8214,500001.0,NEAR OCEAN
19534,-122.21,37.37,34.0,1476.0,217.0,613.0,223.0,8.2883,500001.0,NEAR OCEAN
20374,-122.27,37.48,26.0,3542.0,507.0,1392.0,524.0,8.5184,500001.0,NEAR OCEAN
20466,-117.24,32.85,22.0,3479.0,448.0,1252.0,440.0,10.0707,500001.0,NEAR OCEAN
20492,-117.18,33.02,15.0,3540.0,453.0,1364.0,425.0,13.6623,500001.0,NEAR OCEAN

In [15]:
housing[housing["ocean_proximity"]=="ISLAND"].count()

longitude             5
latitude              5
housing_median_age    5
total_rooms           5
total_bedrooms        5
population            5
households            5
median_income         5
median_house_value    5
ocean_proximity       5
dtype: int64

In [25]:
housing[housing["ocean_proximity"]=="NEAR OCEAN"].loc[:,["median_income"]].mean()

median_income    4.005785
dtype: float64

In [26]:
housing[housing["median_income"] == housing["median_income"].max()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
515,-118.41,34.07,52.0,3562.0,394.0,1163.0,361.0,15.0001,500001.0,<1H OCEAN
549,-118.33,34.07,52.0,1482.0,171.0,531.0,161.0,15.0001,500001.0,<1H OCEAN
613,-118.33,34.06,52.0,1841.0,240.0,693.0,218.0,15.0001,500001.0,<1H OCEAN
793,-122.44,37.79,52.0,1447.0,186.0,483.0,181.0,15.0001,500001.0,NEAR BAY
954,-118.19,34.19,34.0,2061.0,260.0,825.0,254.0,15.0001,500001.0,<1H OCEAN
1068,-118.43,34.08,46.0,778.0,90.0,238.0,93.0,15.0001,500001.0,<1H OCEAN
1821,-121.96,37.13,26.0,50.0,5.0,17.0,4.0,15.0001,400000.0,<1H OCEAN
2526,-122.20,37.44,31.0,2328.0,270.0,722.0,247.0,15.0001,500001.0,NEAR OCEAN
2533,-122.14,37.50,46.0,30.0,4.0,13.0,5.0,15.0001,500001.0,NEAR BAY
3148,-121.59,37.19,52.0,220.0,32.0,55.0,26.0,15.0001,131300.0,<1H OCEAN
3288,-118.41,34.07,52.0,1202.0,142.0,408.0,138.0,15.0001,500001.0,<1H OCEAN
3555,-118.32,34.06,52.0,955.0,100.0,457.0,120.0,15.0001,500001.0,<1H OCEAN
4304,-118.39,34.08,52.0,3759.0,464.0,1407.0,422.0,15.0001,500001.0,<1H OCEAN
4524,-117.87,33.62,15.0,2209.0,275.0,735.0,274.0,15.0001,500001.0,<1H OCEAN
4614,-117.23,32.99,17.0,2718.0,326.0,1011.0,319.0,15.0001,500001.0,NEAR OCEAN
5941,-121.87,37.46,43.0,91.0,12.0,58.0,16.0,15.0001,500001.0,<1H OCEAN
5999,-118.41,34.09,37.0,2716.0,302.0,809.0,291.0,15.0001,500001.0,<1H OCEAN
6786,-118.20,34.19,38.0,2176.0,266.0,798.0,243.0,15.0001,500001.0,<1H OCEAN
7777,-122.36,37.56,32.0,4684.0,540.0,1512.0,511.0,15.0001,500001.0,NEAR OCEAN
7826,-118.44,34.09,36.0,3129.0,392.0,862.0,334.0,15.0001,500001.0,<1H OCEAN
8592,-118.49,34.06,42.0,2861.0,360.0,829.0,310.0,15.0001,500001.0,<1H OCEAN
8799,-122.50,37.79,52.0,8.0,1.0,13.0,1.0,15.0001,500001.0,NEAR BAY
8857,-122.22,37.44,32.0,4281.0,501.0,1318.0,484.0,15.0001,500001.0,NEAR OCEAN
9644,-122.21,37.46,40.0,1777.0,207.0,577.0,207.0,15.0001,500001.0,NEAR OCEAN
9701,-118.10,34.13,47.0,2234.0,276.0,749.0,260.0,15.0001,500001.0,<1H OCEAN
10431,-118.06,34.15,37.0,1980.0,226.0,697.0,226.0,15.0001,500001.0,INLAND
10601,-118.33,34.07,52.0,2248.0,255.0,813.0,265.0,15.0001,500001.0,<1H OCEAN
11068,-118.37,34.10,37.0,407.0,67.0,100.0,47.0,15.0001,500001.0,<1H OCEAN
11369,-122.18,37.46,40.0,2529.0,293.0,831.0,258.0,15.0001,500001.0,NEAR BAY
11501,-122.27,37.43,33.0,1601.0,223.0,629.0,215.0,15.0001,500001.0,NEAR OCEAN
12500,-118.34,33.76,34.0,5586.0,674.0,1871.0,636.0,15.0001,500001.0,NEAR OCEAN
12674,-118.42,34.09,40.0,3552.0,392.0,1024.0,370.0,15.0001,500001.0,<1H OCEAN
12796,-118.40,34.11,32.0,5578.0,753.0,1567.0,697.0,15.0001,500001.0,<1H OCEAN
12837,-118.49,34.05,42.0,1918.0,216.0,632.0,224.0,15.0001,500001.0,<1H OCEAN
13076,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0,<1H OCEAN
13558,-118.12,34.12,52.0,2907.0,317.0,956.0,279.0,15.0001,500001.0,<1H OCEAN
13814,-122.22,37.40,32.0,2297.0,287.0,814.0,283.0,15.0001,500001.0,NEAR OCEAN
14480,-118.34,34.08,52.0,1721.0,195.0,688.0,196.0,15.0001,500001.0,<1H OCEAN
14520,-118.50,34.05,36.0,4152.0,542.0,1461.0,550.0,15.0001,500001.0,<1H OCEAN
14918,-118.42,34.08,48.0,2413.0,261.0,770.0,248.0,15.0001,500001.0,<1H OCEAN
14984,-118.42,34.08,46.0,1399.0,148.0,410.0,152.0,15.0001,500001.0,<1H OCEAN
15857,-118.18,34.19,48.0,1371.0,NaN,528.0,155.0,15.0001,500001.0,<1H OCEAN
16101,-118.06,33.72,14.0,2665.0,331.0,964.0,319.0,15.0001,500001.0,NEAR OCEAN
17773,-118.40,34.08,52.0,3815.0,439.0,1266.0,413.0,15.0001,500001.0,<1H OCEAN
18825,-118.04,34.13,35.0,249.0,31.0,268.0,29.0,15.0001,500001.0,INLAND
19008,-118.50,34.04,52.0,3000.0,374.0,1143.0,375.0,15.0001,500001.0,<1H OCEAN
19881,-118.40,34.10,27.0,3979.0,510.0,1351.0,520.0,15.0001,500001.0,<1H OCEAN
20183,-117.85,33.62,13.0,5192.0,658.0,1865.0,662.0,15.0001,500001.0,<1H OCEAN
20304,-118.40,34.09,45.0,2686.0,283.0,857.0,259.0,15.0001,500001.0,<1H OCEAN

In [27]:
housing[housing["median_house_value"] == housing["median_house_value"].max()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
89,-122.27,37.80,52.0,249.0,78.0,396.0,85.0,1.2434,500001.0,NEAR BAY
103,-118.47,33.99,24.0,1438.0,454.0,665.0,416.0,2.9750,500001.0,<1H OCEAN
105,-118.50,33.97,29.0,2737.0,808.0,1157.0,696.0,5.1280,500001.0,<1H OCEAN
107,-118.39,34.08,27.0,6605.0,1710.0,2665.0,1520.0,3.8088,500001.0,<1H OCEAN
132,-122.34,37.55,44.0,2465.0,328.0,843.0,324.0,6.9533,500001.0,NEAR OCEAN
...,...,...,...,...,...,...,...,...,...,...
20494,-118.12,34.13,52.0,2935.0,341.0,975.0,327.0,11.7060,500001.0,<1H OCEAN
20500,-121.93,37.66,24.0,3166.0,424.0,1081.0,400.0,8.3337,500001.0,<1H OCEAN
20511,-122.05,37.31,25.0,4111.0,538.0,1585.0,568.0,9.2298,500001.0,<1H OCEAN
20515,-117.36,33.17,24.0,2046.0,442.0,812.0,367.0,2.3182,500001.0,NEAR OCEAN
20535,-122.43,37.80,52.0,2802.0,622.0,954.0,572.0,4.5399,500001.0,NEAR BAY

In [28]:
housing.sort_values(
    by="median_house_value",
    ascending=False
)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
11870,-117.91,33.62,35.0,2426.0,359.0,937.0,387.0,9.2175,500001.0,<1H OCEAN
11857,-118.39,34.10,30.0,6310.0,957.0,1776.0,880.0,8.9440,500001.0,<1H OCEAN
11874,-117.86,33.62,23.0,3166.0,411.0,1092.0,345.0,7.9367,500001.0,<1H OCEAN
1431,-118.57,34.27,20.0,7384.0,845.0,2795.0,872.0,9.6047,500001.0,<1H OCEAN
20535,-122.43,37.80,52.0,2802.0,622.0,954.0,572.0,4.5399,500001.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
1504,-118.33,34.15,39.0,493.0,168.0,259.0,138.0,2.3667,17500.0,<1H OCEAN
15088,-117.02,36.40,19.0,619.0,239.0,490.0,164.0,2.1000,14999.0,INLAND
13309,-122.74,39.71,16.0,255.0,73.0,85.0,38.0,1.6607,14999.0,INLAND
5444,-117.86,34.24,52.0,803.0,267.0,628.0,225.0,4.1932,14999.0,INLAND
12793,-123.17,40.31,36.0,98.0,28.0,18.0,8.0,0.5360,14999.0,INLAND

In [29]:
housing.sort_values(
    by="median_income",
    ascending=False
)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
10431,-118.06,34.15,37.0,1980.0,226.0,697.0,226.0,15.0001,500001.0,INLAND
16101,-118.06,33.72,14.0,2665.0,331.0,964.0,319.0,15.0001,500001.0,NEAR OCEAN
10601,-118.33,34.07,52.0,2248.0,255.0,813.0,265.0,15.0001,500001.0,<1H OCEAN
13814,-122.22,37.40,32.0,2297.0,287.0,814.0,283.0,15.0001,500001.0,NEAR OCEAN
8592,-118.49,34.06,42.0,2861.0,360.0,829.0,310.0,15.0001,500001.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
12089,-118.28,33.93,52.0,117.0,33.0,74.0,45.0,0.4999,90600.0,<1H OCEAN
11939,-118.28,34.02,29.0,515.0,229.0,2690.0,217.0,0.4999,500001.0,<1H OCEAN
73,-122.29,37.81,46.0,12.0,4.0,18.0,7.0,0.4999,67500.0,NEAR BAY
419,-123.32,40.43,15.0,661.0,146.0,131.0,57.0,0.4999,56700.0,INLAND
16504,-116.90,34.69,10.0,337.0,102.0,108.0,50.0,0.4999,55000.0,INLAND

In [30]:
numeric_housing = housing.select_dtypes(include="number")

corr_matrix = numeric_housing.corr()

corr_matrix

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,1.000000,-0.924664,-0.108197,0.044568,0.069608,0.099773,0.055310,-0.015176,-0.045967
latitude,-0.924664,1.000000,0.011173,-0.036100,-0.066983,-0.108785,-0.071035,-0.079809,-0.144160
housing_median_age,-0.108197,0.011173,1.000000,-0.361262,-0.320451,-0.296244,-0.302916,-0.119034,0.105623
total_rooms,0.044568,-0.036100,-0.361262,1.000000,0.930380,0.857126,0.918484,0.198050,0.134153
total_bedrooms,0.069608,-0.066983,-0.320451,0.930380,1.000000,0.877747,0.979728,-0.007723,0.049686
population,0.099773,-0.108785,-0.296244,0.857126,0.877747,1.000000,0.907222,0.004834,-0.024650
households,0.055310,-0.071035,-0.302916,0.918484,0.979728,0.907222,1.000000,0.013033,0.065843
median_income,-0.015176,-0.079809,-0.119034,0.198050,-0.007723,0.004834,0.013033,1.000000,0.688075
median_house_value,-0.045967,-0.144160,0.105623,0.134153,0.049686,-0.024650,0.065843,0.688075,1.000000

In [31]:
corr_matrix["median_house_value"].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [32]:
housing.groupby("ocean_proximity")[
    "median_house_value"
].mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [33]:
housing.groupby("ocean_proximity")[
    "median_income"
].mean()

ocean_proximity
<1H OCEAN     4.230682
INLAND        3.208996
ISLAND        2.744420
NEAR BAY      4.172885
NEAR OCEAN    4.005785
Name: median_income, dtype: float64

In [34]:
housing.groupby("ocean_proximity").size()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
ISLAND           5
NEAR BAY      2290
NEAR OCEAN    2658
dtype: int64

In [35]:
housing.groupby("ocean_proximity").value_counts()

ocean_proximity  longitude  latitude  housing_median_age  total_rooms  total_bedrooms  population  households  median_income  median_house_value
<1H OCEAN        -117.04    32.80     11.0                1802.0       440.0           630.0       428.0       2.0337         146700.0              1
                 -118.47    33.99     24.0                1438.0       454.0           665.0       416.0       2.9750         500001.0              1
                 -121.77    37.33     9.0                 3160.0       468.0           1675.0      470.0       7.5443         348400.0              1
                 -118.50    33.97     29.0                2737.0       808.0           1157.0      696.0       5.1280         500001.0              1
                 -118.39    34.08     27.0                6605.0       1710.0          2665.0      1520.0      3.8088         500001.0              1
                                                                                                                                                   ..
NEAR OCEAN       -117.24    32.85     22.0                3479.0       448.0           1252.0      440.0       10.0707        500001.0              1
                 -117.08    32.74     35.0                1434.0       253.0           753.0       228.0       2.3812         135100.0              1
                 -117.18    33.02     15.0                3540.0       453.0           1364.0      425.0       13.6623        500001.0              1
                 -118.15    33.77     36.0                4366.0       1211.0          1912.0      1172.0      3.5292         361800.0              1
                 -117.36    33.17     24.0                2046.0       442.0           812.0       367.0       2.3182         500001.0              1
Name: count, Length: 20433, dtype: int64

In [2]:
#DAY 07
#Handling missing values
housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [2]:
#only no. of bedrooms has missing values (207)
#displaying these rows
housing[housing["total_bedrooms"].isnull()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
182,-118.27,34.04,13.0,1784.0,NaN,2158.0,682.0,1.7038,118100.0,<1H OCEAN
327,-117.65,34.04,15.0,3393.0,NaN,2039.0,611.0,3.9336,151000.0,INLAND
366,-122.50,37.75,44.0,1819.0,NaN,1137.0,354.0,3.4919,271800.0,NEAR OCEAN
477,-117.99,34.14,30.0,2346.0,NaN,1988.0,474.0,2.5625,153000.0,INLAND
495,-114.59,34.83,41.0,812.0,NaN,375.0,158.0,1.7083,48500.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
19880,-118.23,33.94,36.0,1110.0,NaN,1417.0,302.0,2.3333,92100.0,<1H OCEAN
19952,-119.19,34.20,18.0,3620.0,NaN,3171.0,779.0,3.3409,220500.0,NEAR OCEAN
20088,-119.73,36.83,8.0,3602.0,NaN,1959.0,580.0,5.3478,138800.0,INLAND
20325,-118.88,34.17,15.0,4260.0,NaN,1701.0,669.0,5.1033,410700.0,<1H OCEAN
20345,-122.22,38.15,7.0,5129.0,NaN,2824.0,738.0,5.5138,171100.0,NEAR BAY

In [3]:
housing[housing["total_bedrooms"].isnull()].count()

longitude             207
latitude              207
housing_median_age    207
total_rooms           207
total_bedrooms          0
population            207
households            207
median_income         207
median_house_value    207
ocean_proximity       207
dtype: int64

In [3]:
housing_clean = housing.copy()

In [4]:
#filling in missing values
median_bedrooms = housing_clean["total_bedrooms"].median()

housing_clean["total_bedrooms"] = housing_clean["total_bedrooms"].fillna(
    median_bedrooms
)

In [6]:
housing_clean.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [5]:
housing["total_bedrooms"].mean()

np.float64(537.8705525375618)

In [6]:
housing["total_bedrooms"].median()

np.float64(435.0)

In [2]:
pct_missing = housing["total_bedrooms"].isnull().mean() * 100
print(f"Missing values: {pct_missing:.2f}%")

Missing values: 1.00%

In [3]:
housing_dropped = housing.copy()

In [4]:
housing_dropped = housing_dropped.dropna(subset=["total_bedrooms"])

In [10]:
housing_dropped.shape[0]

20433

In [11]:
housing_clean.shape[0]

20640

In [12]:
#Duplication and data quality
housing.duplicated().sum()

np.int64(0)

In [5]:
housing[housing.duplicated()]

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value, ocean_proximity]
Index: []

In [5]:
housing.duplicated(keep="first").sum()

np.int64(0)

In [11]:
housing.duplicated(keep=False).sum()

np.int64(0)

In [40]:
housing_clean.duplicated().sum()

np.int64(0)

In [ ]:
#performed an audit and established that no duplicates are found in the data
#now performing encoding

In [6]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

ocean_encoded = encoder.fit_transform(
    housing[["ocean_proximity"]]
)

In [7]:
print(ocean_encoded.toarray())

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]

In [16]:
print(encoder.categories_)

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
      dtype=object)]

In [8]:
encoder.get_feature_names_out(["ocean_proximity"])

array(['ocean_proximity_<1H OCEAN', 'ocean_proximity_INLAND',
       'ocean_proximity_ISLAND', 'ocean_proximity_NEAR BAY',
       'ocean_proximity_NEAR OCEAN'], dtype=object)

In [8]:
#feature scaling
housing[
    ["median_income", "total_rooms", "population"]
].describe()

       median_income   total_rooms    population
count   20640.000000  20640.000000  20640.000000
mean        3.870671   2635.763081   1425.476744
std         1.899822   2181.615252   1132.462122
min         0.499900      2.000000      3.000000
25%         2.563400   1447.750000    787.000000
50%         3.534800   2127.000000   1166.000000
75%         4.743250   3148.000000   1725.000000
max        15.000100  39320.000000  35682.000000

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(
    housing[["median_income", "total_rooms", "population"]]
)

In [21]:
scaled_data.mean()

np.float64(2.237658809322021e-17)

In [22]:
scaled_data.std()

np.float64(0.9999999999999999)

In [ ]:
#create an ML preprocessing pipeline

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [11]:
#separating input & output
X = housing.drop("median_house_value", axis=1)
y = housing["median_house_value"]

In [12]:
#separate test & train data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [13]:
#divide numerical and categorical features
numerical_features = [
    "longitude",
    "latitude",
    "housing_median_age",
    "total_rooms",
    "total_bedrooms",
    "population",
    "households",
    "median_income"
]

categorical_features = [
    "ocean_proximity"
]

In [14]:
#build numerical pipeline
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [15]:
#build categorical pipeline
categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [16]:
#actual preprocessing
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

In [17]:
#fit on training data
X_train_prepared = preprocessor.fit_transform(X_train)

In [18]:
X_test_prepared = preprocessor.transform(X_test)

In [19]:
print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_prepared.shape)

print("Original test shape:", X_test.shape)
print("Processed test shape:", X_test_prepared.shape)

Original training shape: (16512, 9)
Processed training shape: (16512, 13)
Original test shape: (4128, 9)
Processed test shape: (4128, 13)

In [19]:
#sanity check? lol
import numpy as np

print(np.isnan(X_train_prepared).sum())

0

In [20]:
#feature names
feature_names = preprocessor.get_feature_names_out()

print(feature_names)

['num__longitude' 'num__latitude' 'num__housing_median_age'
 'num__total_rooms' 'num__total_bedrooms' 'num__population'
 'num__households' 'num__median_income' 'cat__ocean_proximity_<1H OCEAN'
 'cat__ocean_proximity_INLAND' 'cat__ocean_proximity_ISLAND'
 'cat__ocean_proximity_NEAR BAY' 'cat__ocean_proximity_NEAR OCEAN']

In [ ]:
#pipeline complete!

In [ ]:
#Day 08
#Building a Linear Regression Model!

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train_prepared, y_train)

LinearRegression()

In [22]:
predictions = model.predict(X_test_prepared)

In [37]:
from sklearn.metrics import root_mean_squared_error

rmse = root_mean_squared_error(y_test, predictions)

print("RMSE:", rmse)

RMSE: 69791.25485613542

In [23]:
print("Predictions:")
print(predictions[:5])

print("\nActual values:")
print(y_test.iloc[:5].to_numpy())

Predictions:
[ 40760.37690828 264870.25618902 384166.49995454 299557.33912545
 248872.23888162]

Actual values:
[ 65600. 353400. 466700. 500001. 286100.]

In [24]:
comparison = pd.DataFrame({
    "Actual": y_test.iloc[:5].to_numpy(),
    "Predicted": predictions[:5]
})

print(comparison)

     Actual      Predicted
0   65600.0   40760.376908
1  353400.0  264870.256189
2  466700.0  384166.499955
3  500001.0  299557.339125
4  286100.0  248872.238882

In [25]:
errors = y_test.to_numpy() - predictions

print("Mean error:", errors.mean())
print("Largest error:", errors.max())
print("Smallest error:", errors.min())

Mean error: 1341.9747781468561
Largest error: 409003.27214151446
Smallest error: -313003.85537905444

In [27]:
absolute_errors = np.abs(errors)

print("Mean absolute error:", absolute_errors.mean())
print("Largest absolute error:", absolute_errors.max())

Mean absolute error: 50752.605868590275
Largest absolute error: 409003.27214151446

In [28]:
print("Underpredictions:", (errors > 0).sum())
print("Overpredictions:", (errors < 0).sum())

Underpredictions: 1708
Overpredictions: 2420

In [ ]:
#Does the model perform differently for cheap versus expensive houses?

In [28]:
cheap = y_test < 200000
expensive = y_test >= 200000

In [29]:
from sklearn.metrics import mean_absolute_error

mae_cheap = mean_absolute_error(
    y_test[cheap],
    predictions[cheap]
)

mae_expensive = mean_absolute_error(
    y_test[expensive],
    predictions[expensive]
)

print("Cheap houses MAE:", mae_cheap)
print("Expensive houses MAE:", mae_expensive)

Cheap houses MAE: 40500.83694463256
Expensive houses MAE: 64532.2407595658

In [30]:
test_analysis = pd.DataFrame({
    "income": X_test["median_income"].values,
    "actual": y_test.values,
    "predicted": predictions,
    "absolute_error": np.abs(y_test.values - predictions)
})

print(test_analysis.sort_values("absolute_error", ascending=False).head(10))

      income    actual      predicted  absolute_error
3745  2.6250  500001.0   90997.727858   409003.272142
1257  1.7679  450000.0   85103.114538   364896.885462
4037  1.1667  500001.0  135305.672281   364695.327719
3200  3.7727  500001.0  145343.867985   354657.132015
3073  0.8804  450000.0  121727.257875   328272.742125
3883  2.5714  500001.0  173469.964458   326531.035542
3400  7.5752   67500.0  380503.855379   313003.855379
309   4.2391  154600.0 -147215.705024   301815.705024
2054  3.2321  390800.0   89888.790012   300911.209988
34    2.7275  500001.0  200467.773148   299533.226852

In [ ]:
#Time for Decision Tree Regressor ig 😀 can another model predict the prices better than linear regression?

In [31]:
from sklearn.tree import DecisionTreeRegressor

In [32]:
tree_model = DecisionTreeRegressor(random_state=42)

In [33]:
tree_model.fit(X_train_prepared, y_train)

DecisionTreeRegressor(random_state=42)

In [34]:
tree_predictions = tree_model.predict(X_test_prepared)

In [38]:
tree_rmse = root_mean_squared_error(
    y_test,
    tree_predictions
)

print("Decision Tree RMSE:", tree_rmse)

Decision Tree RMSE: 68306.66247492214

In [39]:
tree_train_predictions = tree_model.predict(X_train_prepared)

tree_train_rmse = root_mean_squared_error(
    y_train,
    tree_train_predictions
)

print("Training RMSE:", tree_train_rmse)
print("Test RMSE:", tree_rmse)

Training RMSE: 0.0
Test RMSE: 68306.66247492214

In [40]:
#with the hypothesis on the model being too complex (that's why the DT may have overfitted), we experiment with different tree depths to see which depth has the least rmse
depths = [2, 4, 6, 8, 10, 15, 20]

for depth in depths:
    model = DecisionTreeRegressor(
        max_depth=depth,
        random_state=42
    )

    model.fit(X_train_prepared, y_train)

    train_predictions = model.predict(X_train_prepared)
    test_predictions = model.predict(X_test_prepared)

    train_rmse = root_mean_squared_error(
        y_train,
        train_predictions
    )

    test_rmse = root_mean_squared_error(
        y_test,
        test_predictions
    )

    print(
        f"Depth {depth:>2} | "
        f"Train RMSE: ${train_rmse:,.0f} | "
        f"Test RMSE: ${test_rmse:,.0f}"
    )

Depth  2 | Train RMSE: $81,715 | Test RMSE: $84,278
Depth  4 | Train RMSE: $71,953 | Test RMSE: $75,315
Depth  6 | Train RMSE: $64,517 | Test RMSE: $69,382
Depth  8 | Train RMSE: $56,643 | Test RMSE: $63,698
Depth 10 | Train RMSE: $47,979 | Test RMSE: $61,325
Depth 15 | Train RMSE: $24,589 | Test RMSE: $65,392
Depth 20 | Train RMSE: $8,000 | Test RMSE: $67,878

In [ ]:
#depth 10 performs the best

In [41]:
#Cross validation
from sklearn.model_selection import cross_val_score

In [42]:
tree_model = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

scores = cross_val_score(
    tree_model,
    X_train_prepared,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=5
)

In [43]:
rmse_scores = -scores

In [44]:
#mean and std of the CV
print("RMSE scores:", rmse_scores)
print("Mean RMSE:", rmse_scores.mean())
print("Standard deviation:", rmse_scores.std())

RMSE scores: [61426.06286239 60765.64218908 60558.28923935 61550.89714388
 62963.28866637]
Mean RMSE: 61452.836020214774
Standard deviation: 844.3043630041118

In [45]:
#repeating our experiment across different splits
depths = [2, 4, 6, 8, 10, 15, 20]

for depth in depths:
    model = DecisionTreeRegressor(
        max_depth=depth,
        random_state=42
    )

    scores = cross_val_score(
        model,
        X_train_prepared,
        y_train,
        scoring="neg_root_mean_squared_error",
        cv=5
    )

    rmse_scores = -scores

    print(
        f"Depth {depth:>2} | "
        f"Mean RMSE: ${rmse_scores.mean():,.0f} | "
        f"Std: ${rmse_scores.std():,.0f}"
    )

Depth  2 | Mean RMSE: $82,068 | Std: $527
Depth  4 | Mean RMSE: $72,887 | Std: $962
Depth  6 | Mean RMSE: $66,950 | Std: $1,142
Depth  8 | Mean RMSE: $62,843 | Std: $1,096
Depth 10 | Mean RMSE: $61,453 | Std: $844
Depth 15 | Mean RMSE: $65,469 | Std: $892
Depth 20 | Mean RMSE: $68,702 | Std: $1,043

In [ ]:
#this showed that our model with depth 10 was a good choice, and consistent with our previous experiments, showing an RMSE of 61k

In [46]:
#Time for Ensemble Learning! With Random Forests
from sklearn.ensemble import RandomForestRegressor

In [47]:
forest = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [48]:
forest.fit(X_train_prepared, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [49]:
forest_predictions = forest.predict(X_test_prepared)

In [50]:
forest_rmse = root_mean_squared_error(
    y_test,
    forest_predictions
)

print("Random Forest RMSE:", forest_rmse)

Random Forest RMSE: 49483.65059945411

In [51]:
#beautiful! now we should cross-validate that RF too
forest_scores = cross_val_score(
    forest,
    X_train_prepared,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=5
)

forest_rmse_scores = -forest_scores

print("RMSE scores:", forest_rmse_scores)
print("Mean RMSE:", forest_rmse_scores.mean())
print("Standard deviation:", forest_rmse_scores.std())

RMSE scores: [49524.90259689 48605.88765867 49667.27545487 49178.20478958
 49430.34953586]
Mean RMSE: 49281.324007175994
Standard deviation: 373.4556175680738

In [52]:
estimators = [10, 50, 100, 200, 500]

for n in estimators:
    forest = RandomForestRegressor(
        n_estimators=n,
        random_state=42,
        n_jobs=-1
    )

    scores = cross_val_score(
        forest,
        X_train_prepared,
        y_train,
        scoring="neg_root_mean_squared_error",
        cv=5
    )

    rmse_scores = -scores

    print(
        f"Trees {n:>3} | "
        f"Mean RMSE: ${rmse_scores.mean():,.0f} | "
        f"Std: ${rmse_scores.std():,.0f}"
    )

Trees  10 | Mean RMSE: $51,800 | Std: $455
Trees  50 | Mean RMSE: $49,568 | Std: $393
Trees 100 | Mean RMSE: $49,281 | Std: $373
Trees 200 | Mean RMSE: $49,186 | Std: $444
Trees 500 | Mean RMSE: $49,107 | Std: $433

In [53]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

models = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        max_depth=10,
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    )
}

In [54]:
for name, model in models.items():

    scores = cross_val_score(
        model,
        X_train_prepared,
        y_train,
        scoring="neg_root_mean_squared_error",
        cv=5
    )

    rmse_scores = -scores

    print(f"\n{name}")
    print(f"RMSE scores: {rmse_scores}")
    print(f"Mean RMSE: ${rmse_scores.mean():,.0f}")
    print(f"Std: ${rmse_scores.std():,.0f}")

Linear Regression
RMSE scores: [69912.03560007 66798.44906581 69452.47938178 67930.46349445
 68881.11191997]
Mean RMSE: $68,595
Std: $1,115

Decision Tree
RMSE scores: [61426.06286239 60765.64218908 60558.28923935 61550.89714388
 62963.28866637]
Mean RMSE: $61,453
Std: $844

Random Forest
RMSE scores: [49563.00922605 48383.99306765 49604.51013391 49074.92349959
 49301.15103007]
Mean RMSE: $49,186
Std: $444

In [ ]:
# Q. compare our three main models properly using the same validation methodology.
"""
ah... validation methodology

Our evaluation criterion throughout has been "lower RMSE = better model." Methodology was more like:

Use RMSE to measure prediction error, evaluate models on unseen data, use cross-validation to make model comparisons more reliable, and tune hyperparameters based on validation performance while keeping the final test set separate.

By using RMSE we've determined that LR was far off from the scale of answers (Mean RMSE: $68,595), so we wondered if DT would be a better. It can model nonlinear relationships and feature interactions without assuming a linear relationship between the inputs and target.

Naturally, it did a <1% improvement on our model. (68306.66247492214) So we tuned its hyperparameters, ran some tests with different depths, and got (Test RMSE: $61,325) which was much more significant than our previous unrefined version.12.1% lower RMSE. We confirmed that with corss-validation (different depths, different training sets) and got the same best score.

Then we thought that if decision tree worked better, than a better version of it with even more diversity, would work too. so we brought in RF, tested on different n_estimators, and concluded our experiment with a new best; Mean RMSE: $49,186 at 200 trees. Going any higher was not a computationally smart move, so we decide to stop here.

Thus, using consistent validation procedures and cross-validation where appropriate., we've managed to improve our prediction results by 29.52% which is considerably significant than our original one.
"""

In [ ]:
# Q. Which model would you select, and what evidence supports your decision?
"""
selecting the model would be based on how the model will be used in production, but more importantly; a useful model is one with more accurate predictions. 
for the best mean RMSE, naturally I'd be choosing random forest. which also showed the least standard deviation (consistent with good rmse). 
However, computationally it might not be ideal. Then decision tree mighttt be ideal, but with a jump from 61k to 49k? 
i think a higher computational cost might be worth the output's better accuracy. as for model complexity, I think RF was also the most complex model, but that also means that we can try to improve it using max_features and other hyperparameter tuning. 
Wouldn't that be fruitful for our goal?
"""